// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD7nb1VDPmk0RZAkigeI7TGvyCYKqA1GM',
    appId: '1:282023383037:web:2257cdafa4fd5aa6a2d394',
    messagingSenderId: '282023383037',
    projectId: 'realtech-981b9',
    authDomain: 'realtech-981b9.firebaseapp.com',
    storageBucket: 'realtech-981b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7zaN0iecS7ypXuBaW07CgE2bmKm4GS-A',
    appId: '1:282023383037:android:a0ef0c4f89ef1f0da2d394',
    messagingSenderId: '282023383037',
    projectId: 'realtech-981b9',
    storageBucket: 'realtech-981b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDEHvkLzj-TIgUshLYpeEg81LBWxc4Np4',
    appId: '1:282023383037:ios:d0976f55a3cee6caa2d394',
    messagingSenderId: '282023383037',
    projectId: 'realtech-981b9',
    storageBucket: 'realtech-981b9.appspot.com',
    iosBundleId: 'com.example.realtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDEHvkLzj-TIgUshLYpeEg81LBWxc4Np4',
    appId: '1:282023383037:ios:028ed7068378eec0a2d394',
    messagingSenderId: '282023383037',
    projectId: 'realtech-981b9',
    storageBucket: 'realtech-981b9.appspot.com',
    iosBundleId: 'com.example.realtech.RunnerTests',
  );
}
